export const MENUS = {
  MANAGEMENTS: ["user-management", "role-management", "company-management"],
  BULK_UPLOADS: [
    "bulk-upload-for-subscriber-profile",    
    "bulk-upload-for-watch-list",
    "bulk-upload-for-black-list",
    "bulk-upload-for-wallet-accounts",
  ],
  REPORTS: [
    "reports",
    "kyc-pending-reports",
    "kyc-approval-reports",
    "kyc-rejection-reports",
    "kyc-mobile-account-reports",
    "kyc-otc-reports",
    "kyc-performance-reports",
    "kyc-modified-type-approval-reports",
    "kyc-status-summary-reports",
  ],
  OTCS: [
    "all-otc-profiles",
    "approved-otc-profiles",
    "pending-to-approve-otc-profiles",
    "pending-to-review-edited-otc-profiles",
    "pending-to-recommend-otc-profiles",
    "recommend-to-approve-otc-profiles",
    "recommend-to-reject-otc-profiles",
    "rejected-otc-profiles",
  ],
  SUBSCRIBERS: [
    "add-new-subscriber",
    "add-foreign-subscriber",
    "all-subscribers",
    "KYC-not-submitted-subscribers",
    "pending-to-approve-subscribers",
    "pending-to-recommend-subscribers",
    "pending-review-edited-subscribers",
    "recommend-to-approve-subscribers",
    "recommend-to-reject-subscribers",
    "approved-subscribers",
    "rejected-subscribers",
  ],
  SETTINGS: ["configrations", "reasons"],
};
