export const ROLES = {
  ALL: [
    "DB-1",
    "DB-2",
    "UM-R-1",
    "UM-R-2",
    "UM-C-1",
    "UM-U-1",
    "UM-U-3",
    "UM-U-2",
    "CM-R-1",
    "CM-R-2",
    "CM-U-1",
    "CM-U-2",
    "CM-C-1",
    "RM-R-1",
    "RM-R-2",
    "RM-U-1",
    "RM-C-1",
    "OTC-A-1",
    "OTC-R-1",
    "OTC-R-2",
    "OTC-R-3",
    "OTC-R-4",
    "OTC-R-5",
    "OTC-R-6",
    "OTC-R-7",
    "OTC-E-1",
    "OTC-E-2",
    "OTC-C-1",
    "OTC-C-2",
    "OTC-C-3",
    "OTC-C-4",
    "OTC-C-5",
    "OTC-C-6",
    "OTC-C-7",
    "AT-1",
    "AT-2",
    "DE-1",
    "DE-2",
    "DE-3",
    "BU-R-1",
    "BU-C-1",
    "BU-C-2",
    "BU-CS-1",
    "BU-R-2",
    "BU-C-7",
    "BU-CS-4",
    "BU-R-3",
    "BU-CS-2",
    "BU-CS-3",
    "BU-R-4",
    "BU-C-7",
    "BU-CS-5",
    "SB-R-1",
    "SBC-R-2",
    "SBC-R-3",
    "SBC-R-4",
    "SBC-R-5",
    "SBC-R-6",
    "SBC-R-7",
    "SBC-R-8",
    "SBC-R-9",
    "SBC-U-2",
    "SBC-U-3",
    "SBC-CS-2",
    "SBC-CS-3",
    "SBC-CS-4",
    "SBC-CS-5",
    "SBC-CS-6",
    "SBC-CS-7",
    "SBC-CS-8",
    "SBC-CS-9",
    "SBC-C-1",
    "SBC-C-2",
    "SBC-U-4",
    "SBC-U-5",
    "RP-R-1",
    "Cf-R-1",
    "Cf-W-1",
    "RE-R-1",
    "RE-W-1",
  ],
  DASHBOARD: {
    READ: ["DB-1", "DB-2"],
    OTC_DASHBOARD: ["DB-1"],
    SUBSCRIBER_DASHBOARD: ["DB-2"],
  },
  PORTAL_USER: {
    READ: ["UM-R-1", "UM-R-2", "UM-C-1", "UM-U-1", "UM-U-2"],
    CREATE: ["UM-C-1"],
    UPDATE: ["UM-U-1"],
    RESET_PASSWORD: ["UM-U-2"],
  },

  COMPANY: {
    READ: ["CM-R-1", "CM-R-2", "CM-U-1", "CM-C-1"],
    CREATE: ["CM-C-1"],
    UPDATE: ["CM-U-1"],
  },

  ROLE: {
    READ: ["RM-R-1", "RM-R-2", "RM-U-1", "RM-C-1"],
    CREATE: ["RM-C-1"],
    UPDATE: ["RM-U-1"],
  },

  OTC: {
    ALL_READ: [
      "OTC-A-1",
      "OTC-R-1",
      "OTC-R-2",
      "OTC-R-3",
      "OTC-R-4",
      "OTC-R-5",
      "OTC-R-6",
      "OTC-R-7",
      "OTC-E-1",
      "OTC-E-2",
      "OTC-C-1",
      "OTC-C-2",
      "OTC-C-3",
      "OTC-C-4",
      "OTC-C-5",
      "OTC-C-6",
      "OTC-C-7",
    ],
    ALL_PROFILE: {
      READ: ["OTC-A-1"],
    },
    PENDING_APPROVE: {
      READ: ["OTC-R-1", "OTC-E-1", "OTC-C-1"],
      UPDATE: ["OTC-E-1"],
      ACCEPT_REJECT: ["OTC-C-1"],
      UPDATE_STATUS: ["OTC-C-7"],
    },
    APPROVED: {
      READ: ["OTC-R-2", "OTC-E-2"],
      UPDATE: ["OTC-E-2"],
    },
    REJECTED: {
      READ: ["OTC-R-3"],
    },
    PENDING_REVIEW: {
      READ: ["OTC-R-4", "OTC-C-3"],
      ACCEPT_REJECT: ["OTC-C-3"],
    },
    PENDING_RECOMMEND: {
      READ: ["OTC-R-5", "OTC-C-4"],
      ACCEPT_REJECT: ["OTC-C-4"],
    },
    RECOMMEND_REJECT: {
      READ: ["OTC-R-6", "OTC-C-5"],
      REJECTED: ["OTC-C-5"],
    },
    RECOMMEND_APPROVE: {
      READ: ["OTC-R-7", "OTC-C-6"],
      ACCEPTED: ["OTC-C-6"],
    },
  },
  AUDIT_TRAIL: {
    READ: ["AT-1", "AT-2"],
  },
  DOWNLOAD: {
    EXPORT_DATA: ["DE-1"],
    DOWNLOAD_IMG: ["DE-2"],
    DOWNLOAD_PROFILE: ["DE-3"],
  },

  BULK_UPLOAD: {
    ALL: [
      "BU-R-1",
      "BU-C-1",
      "BU-C-2",
      "BU-CS-1",
      "BU-R-2",
      "BU-C-7",
      "BU-CS-4",
      "BU-R-3",
      "BU-CS-2",
      "BU-CS-3",
      "BU-R-4",
      "BU-C-7",
      "BU-CS-5",
    ],
    SUBSCRIBER: {
      READ: ["BU-R-1", "BU-C-1", "BU-C-2", "BU-CS-1"],
      CREATE: ["BU-C-1"],
      UPDATE: ["BU-C-2"],
      ACCEPT_REJECT: ["BU-CS-1"],
    },
    WATCHLIST: {
      READ: ["BU-R-2", "BU-C-7", "BU-CS-4"],
      CREATE: ["BU-C-7"],
      ACCEPT_REJECT: ["BU-CS-4"],
    },
    WALLET_ACCOUNT: {
      READ: ["BU-R-3", "BU-CS-2", "BU-CS-3"],
      CREATE: ["BU-CS-2"],
      ACCEPT_REJECT: ["BU-CS-3"],
    },
    BLACKLIST: {
      READ: ["BU-R-4", "BU-C-7", "BU-CS-5"],
      CREATE: ["BU-C-7"],
      ACCEPT_REJECT: ["BU-CS-5"],
    },
  },

  SUBSCRIBER: {
    ALL_READ: [
      "SB-R-1",
      "SBC-R-2",
      "SBC-R-3",
      "SBC-R-4",
      "SBC-R-5",
      "SBC-R-6",
      "SBC-R-7",
      "SBC-R-8",
      "SBC-R-9",
      "SBC-U-2",
      "SBC-U-3",
      "SBC-CS-2",
      "SBC-CS-3",
      "SBC-CS-4",
      "SBC-CS-5",
      "SBC-CS-6",
      "SBC-CS-7",
      "SBC-CS-8",
      "SBC-CS-9",
      "SBC-C-1",
      "SBC-C-2",
      "SBC-U-4",
      "SBC-U-5",
    ],

    DEBORD: ["SBC-U-4"],
    ONBORD: ["SBC-U-5"],
    CREATE_ACCOUNT: ["SBC-C-1"],

    ADD_SUBSCRIBER: {
      REGULAR_PROFILE: ["SBC-C-1"],
      BUSINESS_PROFILE: ["SBC-C-2"],
    },
    ALL_PROFILE: {
      READ: ["SBC-R-9"],
    },
    NOT_SUBMITTED: {
      READ: ["SBC-R-8"],
    },
    PENDING_APPROVE: {
      READ: ["SB-R-1", "SBC-U-2", "SBC-CS-2", "SBC-CS-5", "SBC-CS-8"],
      UPDATE: ["SBC-U-2"],
      ACCEPT: ["SBC-CS-2"],
      RECOMMEND: ["SBC-CS-5"],
      REJECT: ["SBC-CS-8"],
      UPDATE_STATUS: ["SBC-CS-9"],
    },
    APPROVED: {
      READ: ["SBC-R-2", "SBC-U-3"],
      UPDATE: ["SBC-U-3"],
    },
    REJECTED: {
      READ: ["SBC-R-3"],
    },
    PENDING_REVIEW: {
      READ: ["SBC-R-4", "SBC-CS-3", "SBC-CS-4"],
      ACCEPT: ["SBC-CS-3"],
      REJECT: ["SBC-CS-4"],
    },
    PENDING_RECOMMEND: {
      READ: ["SBC-R-5", "SBC-CS-5"],
      ACCEPT_REJECT: ["SBC-CS-5"],
    },
    RECOMMEND_REJECT: {
      READ: ["SBC-R-6", "SBC-CS-6"],
      REJECTED: ["SBC-CS-6"],
    },
    RECOMMEND_APPROVE: {
      READ: ["SBC-R-7", "SBC-CS-7"],
      ACCEPTED: ["SBC-CS-7"],
    },
  },

  REPORT: {
    ALL: ["RP-R-1"],
  },

  SETTING: {
    ALL: ["Cf-R-1", "Cf-W-1", "RE-R-1", "RE-W-1"],
    CONFIG: {
      READ: ["Cf-R-1", "Cf-W-1"],
      UPDATE: ["Cf-W-1"],
    },
    REASON: {
      READ: ["RE-R-1", "RE-W-1"],
      WRITE: ["RE-W-1"],
    },
  },
};
